### PR TITLE
make changes using animation.

### LINKED ISSUE #1: Some Changes using Css properties.
can u assign me this.

### PR DESCRIPTION
**Pull request by dvig14**
Screenshot (10)
Screenshot (11)
Screenshot (12)

### CODE REVIEW

**Comment by gouthamrajesh** [comment]
Please provide the details that need to be added in the 'CONTRIBUTORS.md'

**Comment by dvig14** [comment]
Details? About what like I am new to open source so don't know much about
it...

**Comment by gouthamrajesh** [comment]
Not a problem, please provide your following details and we'll do the rest.
Name :
Location :
Bio : 
Github Username : 
Github URL :

**Comment by dvig14** [comment]
Name:Diksha
Location:Gurdaspur
Bio:Btech cse 3rd yr student(Female)
       Gndu regional campus gurdaspur
Github username:dvig14
Github url:https://github. com/dvig14

**Pull request merged**
